### ISSUE TITLE
Plugin Installation on SonarQube Version 6.7.2 Fails

### ISSUE THREAD

**Issue by chbieri** [devcon5io/mutation-analysis-plugin#2]
Plugin installation through marketplace fails on fresh unzipped sonarqube-6.7.2 with error
"No compatible plugin found."

![mutation_analysis_plugin_installation_fail](https://user-images.githubusercontent.com/10205854/43384198-982ba9aa-93dd-11e8-8676-1dc7f176f816.png)

**Comment by chbieri** [comment]
Manual installation succeeds.

**Comment by gmuecke** [comment]
The update-center data has been updated by SonarSource. I verified with 6.7.4, works now ok.
