### ISSUE TITLE
Compatibility is broken with SonarQube 7.6

### ISSUE THREAD

**Issue by varrocen** [devcon5io/mutation-analysis-plugin#25]
I have upgrade my SonarQube to 7.6 and now I have an error when I scan my project:

```
ERROR: Error during SonarQube Scanner execution
ERROR: ch.devcon5.sonar.plugins.mutationanalysis.sensors.PitestSensor has unsatisfied dependency 'class org.sonar.api.profiles.RulesProfile' for constructor 'public ch.devcon5.sonar.plugins.mutationanalysis.sensors.PitestSensor(org.sonar.api.config.Configuration,org.sonar.api.profiles.RulesProfile,org.sonar.api.batch.fs.FileSystem)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@55b62629:45<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6c2c1385:353<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@585ac855:39<|
```

**Comment by gmuecke** [comment]
Hi varrocen, thank you for reporting. I can reproduce & confirm the issue and will work on a fix in the next days.

**Comment by gmuecke** [comment]
It seemed, other plugins had similar issues with the RulesProfile dependency. 
- https://community.sonarsource.com/t/unsatisfied-dependency-in-sq-7-6/6244/5
- https://github.com/spotbugs/sonar-findbugs/issues/218

Solution would be to use the ActiveRules instead. I tried it locally, looks promising. But I need some more tests. But I'm positive I can provide a fix beginning of the upcoming week.

**Comment by varrocen** [comment]
Hi ! Thank you for your fix.

**Comment by abego** [comment]
I saw you put the issue in Done in Release 1.4. When do you plan to do the release/publish it?

**Comment by gmuecke** [comment]
I'm finalizing some tests, I think I'll release it this week.
