### ISSUE TITLE
Update to Jacoco Version needed for Kotlin Support

### ISSUE THREAD

**Issue by johnsingh1977** [devcon5io/mutation-analysis-plugin#31]
I can execute pitest using gradle and pitest gradle plugin successfully. When I attempt to send to sonarqube I get

Line 44 is out of range in the file src/main/kotlin/com/<some package>/Runner.kt (lines: 43)

I traced this to a Jacoco issue. To resolve this, the version should be updated to 0.8.3 in the pom.xml

I am running against sonarqube 7.6 with the latest version of the sonar pitest plugin

**Comment by gmuecke** [comment]
Hi John,
I don't see yet a connection between the jacoco plugin used in the mutation-analysis-plugin for _building_/_testing_ the plugin itself and using it for ... analysing a Kotlin project? (I'm guessing here) 
Could you please provide a bit more details on the error and how it's related to the jacoco plugin - which is not shipped as dependency?
Probably it's an issue in the project you're trying to analyse, and not with the mutation-analysis-pluing.

**Comment by gmuecke** [comment]
I'm closing this issue as there is no connection between jacoco version used to build&test the plugin an the jacoco version used in projects that get analysed _by_ the plugin.
