### ISSUE TITLE
Does not compile with java 11

### ISSUE THREAD

**Issue by magwas** [devcon5io/mutation-analysis-plugin#38]
We are using the standalone analysis feature/branch of the plugin. Which means I have to compile it for myself, in an environment where the java version is 11. ( https://github.com/kode-konveyor/toolchain )
This functionality is a part of a standardized toolchain currently used by 7 other projects.
Our policy views having local changes to other people's code as a temporary workaround: we are willing to do whatever is needed to get the change upstream, and we fork the project as last resort.

Java 8 is being deprecated, in extended support right now.  "Java SE 8 has gone through the End of Public Updates process for legacy releases.  Oracle will continue to provide free public updates and auto updates of Java SE 8 from Oracle at java.com, until at least the end of December 2020 for Personal, Development and other Users."  https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

Java 11 is the current LTS, with premier support until September 2023 and extended support until September 2026.

In the long run support for java 11 will be needed anyway.

The pull request addressing this issue is at https://github.com/devcon5io/mutation-analysis-plugin/pull/34

**Comment by gmuecke** [comment]
First of all, now I see your problem and also appreciate that you contribute to the upstream project. Thank you! 
I'm also going to merge the PR into the standalone-analysis branch. 

But also note, that there are no current plans to integrate the standalone-analysis into the trunk and produce a pre-compiled standalone jar as some preconditions aren't met (i.e. the project structure has to be changed to create two separate build artifacts etc - I haven't wrapped my head around this)
