### ISSUE TITLE
Path problem after upgrade from Sonar 7.9 to 8.9

### ISSUE THREAD

**Issue by jclements2** [devcon5io/mutation-analysis-plugin#54]
We upgraded from Sonar Enterprise 7.9 to 8.9 this week and are now seeing an issue with the mutation plugin. The mutation metric appears under the "measures" tab, but it always shows 0% despite there clearly being mutation reports under the pit-test directory. It appears that the plugin is having an issue resolving the top level path for the build directory.

[INFO] 19:52:42.720 Pitest Sensor [java, kotlin] running on [key=com.jbhunt.finance:ws_finance_billing_axs_tasks] in /dockeragents/sw/ADOAgents/ADOAgent3/_work/1315/s
[DEBUG] 19:52:42.721 Reading mutants
[DEBUG] 19:52:42.724 Searching project root for /dockeragents/sw/ADOAgents/ADOAgent3/_work/1315/s
[INFO] 19:52:42.776 Could not determine project root of /dockeragents/sw/ADOAgents/ADOAgent3/_work/1315/s from parent
[DEBUG] 19:52:42.781 Could not resolve module paths for pom /dockeragents/sw/ADOAgents/ADOAgent3/_work/1315/pom.xml
java.nio.file.NoSuchFileException: /dockeragents/sw/ADOAgents/ADOAgent3/_work/1315/pom.xml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)

**Comment by gmuecke** [comment]
Hi @jclements2,
I can't provide support for the enterprise edition for free, most of all, because I don't have access to these editions. 
But as I am about to upgrade the plugin to support the latest LTS and newer version - could you verify, if the same behavior exists for the Community edition?

Thanks,
Gerald

**Comment by jclements2** [comment]
This turned out to be a config issue on my end, my apologies. I'll close this now, and thanks for the response, much appreciated and thank you for your work on this plugin, it's very helpful.

Jeremy
