### ISSUE TITLE
No test kill ratio value sent when Sonarqube call's webhooks

### ISSUE THREAD

**Issue by aaguila** [devcon5io/mutation-analysis-plugin#56]
### **Context**

When Sonarqube makes a new analysis it call's to our webhook with the analysis results. The problem is in the test kill ratio information, sonar send a body without value.

Example:
```
     {
        "metric": "dc5_mutationAnalysis_mutations_testkill_ratio",
        "operator": "GREATER_THAN",
        "status": "NO_VALUE",
        "errorThreshold": "0"
      }
```

Mutation analisys is being done correctly:

![image](https://user-images.githubusercontent.com/6283257/140475908-cd49af25-5ba2-4907-bff5-1b49c60caa35.png)

### **Data**
**Sonarqube version:** 8.9.3
**Mutation analysis plugin version:** 1.5

**Comment by gmuecke** [comment]
I'm not sure if this is a bug in SQ.
Closing it
