### ISSUE TITLE
Why are issues duplicated in Sonar?

### ISSUE THREAD

**Issue by carmeloquilez** [devcon5io/mutation-analysis-plugin#70]
Hi,

I'm wondering, why are issues duplicated in Sonar? Is there some reason for that?

![image](https://user-images.githubusercontent.com/78669012/188921866-00bbfa65-8551-4a14-868e-8dbedea07278.png)

Best regards.

**Comment by gmuecke** [comment]
As you could see in the screenshot, every mutator-specific rule comes in two "flavors": Category "Bug" and Category "Code Smell". So it gives you different option for how you treat survived mutatants in your projects. Only active one rule (either Bug or Code Smell) in your Quality Profile for each mutator
