### ISSUE TITLE
Pitest reports not recognized by plugin in sonarqube version 10.3

### ISSUE THREAD

**Issue by thisismata** [devcon5io/mutation-analysis-plugin#75]
I installed the plugin from sonarqube market place, and the report directory is correct (I used relative dir), however I couldn't see the mutation analysis on sonarqube. Could someone help me about the version compatibility? Thanks!
<img width="1254" alt="image" src="https://github.com/devcon5io/mutation-analysis-plugin/assets/10822933/a4f2e287-e0ab-42b7-9568-f11ab073c5de">
<img width="793" alt="image" src="https://github.com/devcon5io/mutation-analysis-plugin/assets/10822933/80870892-c88e-488a-a28d-3cf30e4be4d1">
<img width="384" alt="image" src="https://github.com/devcon5io/mutation-analysis-plugin/assets/10822933/db83b6fa-61fc-4739-9247-fb2d2c95a22a">

**Comment by thisismata** [comment]
hi @gmuecke would you please take a look at this issue? Thank you!

**Comment by gmuecke** [comment]
Hi @thisismata ,
please provide the logs of the maven execution
