### ISSUE TITLE
Improve Multi-Modules Maven Support

### ISSUE THREAD

**Issue by gmuecke** [devcon5io/mutation-analysis-plugin#9]
The current support for Maven multi-module projects is very basic. There are several TODOs in the code that need to be addressed:

- add support for modules that are activated by profile (currently those modules are ignored)
- add option to explicitly define the root module (currently it's determined via parent folder relationship)
- add support for determining parent module defined by relative path (currently the parent module must be the parent folder)

(see https://github.com/devcon5io/mutation-analysis-plugin/blob/master/src/main/java/ch/devcon5/sonar/plugins/mutationanalysis/sensors/ReportCollector.java )

**Comment by dmbloch** [comment]
Is it possible to include Gradle support with this change?
https://gradle-pitest-plugin.solidsoft.info/

**Comment by gmuecke** [comment]
@dmbloch I'd prefer a separate issue for this. The improvements for maven multi-module support target at maven specific features (relative paths, profiles, explicit root module).
I opened https://github.com/devcon5io/mutation-analysis-plugin/issues/21 for that purpose.

**Comment by gmuecke** [comment]
I will skip the profile support for the moment, as it will reach too far into the maven internals to which I don't have proper access from the sonarqube plugin.
